Correction du bug crash Serveur
lduf/dijkstra_go pull request #13
Opened 2020-12-29 16:57 UTC by lduf

Closed #10 

Correction du bug crash Serveur
Écrasage du fichier lors de l'écriture avec Client.go

2020-12-29 17:02 UTC, lduf reviewed
À la relecture ça me semble ok,
Il faut que les reviewer test chez eux avec plusieurs fichiers pour voir si 

- [ ] Les résultats du Dijkstra sont bons
- [ ]  Pas de crash serveur

2020-12-30 10:22 UTC, mathisfchx requested changes
index out of range quand on utilise Client.go sans argument et pas la belle formule d'explication
--> à corriger

2020-12-30 10:36 UTC, mathisfchx approved these changes

2020-12-30 10:39 UTC, lduf reviewed
Ca me semble ok

2020-12-30 10:39 UTC, merged